services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/lcdr
      - ./node_modules:/lcdr/node_modules

  base_db:
    image: neo4j:latest
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    restart: always
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
