name: Test

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.6', '7.4', '8.0', '8.1', '8.2', '8.3']

    name: Unit tests on PHP ${{ matrix.php-version }}

    continue-on-error: ${{ matrix.php-version == '8.3' }}

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: 'Validate composer.json'
        run: composer validate --strict

      - name: 'Validate PHP syntax'
        run: php -l src/db.php

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Run tests
        run: composer test


