name: Discussão
description: Discussão sobre algum tópico
title: "[Discussão]: "
labels: ["discussão"]
assignees:
  - hgodinho
body:
  - type: markdown
    attributes:
      value: |
        Preencha o formulário abaixo para adicionar uma nova discussão.
  - type: input
    id: contact
    attributes:
      label: Contato
      description: Como podemos entrar em contato para mais informações?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: page
    attributes:
      label: Página
      description: Sobre qual página você deseja comentar?
      options:
        - Tabelas
        - Entidades
        - Metadata
        - Conceitos pré-definidos
        - Glossário
    validations:
      required: true
  - type: input
    id: topic
    attributes:
      label: Tópico
      description: Qual tópico da página você deseja comentar?
      placeholder: ex. AgentType
  - type: textarea
    id: what-happened
    attributes:
      label: Comentário
      value: "..."
    validations:
      required: true