name: Deploy MDORIM to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-mdorim.yml"
      - "apps/mdorim-docs/**"
      - "packages/mdorim/**"
      - "packages/pub-gen/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.14.1
      - name: Install monorepo dependencies
        run: pnpm install
      - name: Build monorepo packages
        run: pnpm build --scope "@elucidario/mdorim" --scope "@elucidario/pub-gen" --scope "@elucidario/mdorim-docs"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: apps/mdorim-docs/build
