name: Version bump

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm
        uses: pnpm/action-setup@v4

      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: install
        run: pnpm install

      - name: release
        uses: changesets/action@v1
        id: changeset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        if: steps.changeset.outputs.hasChangesets == 'false'
        uses: ./.github/workflows/deploy-site.yaml@main
